apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 80            # for digital ocean
    nodePort: 30001     # for minikube
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: hello-world
